version: '3.8'

services:
  backend:
    build:
      context: ../VyuhShastra-Backend
    ports:
      - "80:5000"
    volumes:
      - ../VyuhShastra-Backend:/app
    environment:
    - FLASK_ENV=development
    - FLASK_DEBUG=True
      
  frontend:
    build:
      context: ./react-ui
    ports:
      - "3000:3000"
    volumes:
      - ./react-ui:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
